const nationalityToCountry = {
  "Algerian": "Algeria",
  "American": "United States of America",
  "Angolan": "Angola",
  "Anmatyerr [Australian]": "Australia",
  "Australian": "Australia",
  "Austrian": "Austria",
  "Azerbaijani": "Azerbaijan",
  "Bahamian": "Bahamas",
  "Bangladeshi": "Bangladesh",
  "Belgian": "Belgium",
  "Beninese": "Benin",
  "Afghan": "Afghanistan",
  "Albanian": "",  "Albanian": "Albania",
  "Bosnian": "Bosnia and Herzegovina",
  "Brazilian": "Brazil",
  "British": "United Kingdom",
  "Bulgarian": "Bulgaria",
  "Burkinabé": "Burkina Faso",
  "Cambodian": "Cambodia",
  "Cameroonian": "Cameroon",
  "Canadian": "Canada",
  "Canadian Inuit": "Canada",
  "Caribbean": "Jamaica",
  "Catalan": "Spain",
  "Central African": "Central African Republic",
  "Chilean": "Chile",
  "Chinese": "China",
  "Colombian": "Colombia",
  "Congolese": "Democratic Republic of the Congo",
  "Coptic": "Egypt",
  "Costa Rican": "Costa Rica",
  "Croatian": "Croatia",
  "Cuban": "Cuba",
  "Cypriot": "Cyprus",
  "Czech": "Czech Republic",
  "Czechoslovakian": "Czech Republic",
  "Danish": "Denmark",
  "Dominican": "Dominican Republic",
  "Dutch": "Netherlands",
  "Ecuadorian": "Ecuador",
  "Egyptian": "Egypt",
  "Emirati": "United Arab Emirates",
  "English": "United Kingdom",
  "Estonian": "Estonia",
  "Ethiopian": "Ethiopia",
  "Filipino": "Philippines",
  "Finnish": "Finland",
  "French": "France",
  "French-Ivorian": "Ivory Coast",
  "Georgian": "Georgia",
  "German": "Germany",
  "Ghanaian": "Ghana",
  "Greek": "Greece",
  "Guatemalan": "Guatemala",
  "Haitian": "Haiti",
  "Hmong": "Laos",
  "Hungarian": "Hungary",
  "Icelandic": "Iceland",
  "Indian": "India",
  "Indonesian": "Indonesia",
  "Iranian": "Iran",
  "Iraqi": "Iraq",
  "Irish": "Ireland",
  "Israeli": "Israel",
  "Italian": "Italy",
  "Ivatan": "Philippines",
  "Ivorian": "Ivory Coast",
  "Jamaican": "Jamaica",
  "Japanese": "Japan",
  "Kalaaleq": "Greenland",
  "Kenyan": "Kenya",
  "Korean": "South Korea",
  "South Korean": "South Korea",
  "Kuwaiti": "Kuwait",
  "Kyrgyz": "Kyrgyzstan",
  "Latvian": "Latvia",
  "Lebanese": "Lebanon",
  "Lithuanian": "Lithuania",
  "Luxembourger": "Luxembourg",
  "Macedonian": "Macedonia",
  "Malaysian": "Malaysia",
  "Malian": "Mali",
  "Mexican": "Mexico",
  "Moroccan": "Morocco",
  "Mozambican": "Mozambique",
  "Namibian": "Namibia",
  "Native American": "United States of America",
  "Nepali": "Nepal",
  "New Zealander": "New Zealand",
  "Nicaraguan": "Nicaragua",
  "Nigerian": "Nigeria",
  "Norwegian": "Norway",
  "Ojibwe": "United States of America",
  "Okinawan": "Japan",
  "Oneida": "United States of America",
  "Pakistani": "Pakistan",
  "Palestinian": "Palestine",
  "Panamanian": "Panama",
  "Paraguayan": "Paraguay",
  "Persian": "Iran",
  "Peruvian": "Peru",
  "Polish": "Poland",
  "Portuguese": "Portugal",
  "Puerto Rican": "Puerto Rico",
  "Romanian": "Romania",
  "Russian": "Russia",
  "Sahrawi": "Western Sahara",
  "Salvadoran": "El Salvador",
  "Scottish": "United Kingdom",
  "Senegalese": "Senegal",
  "Serbian": "Serbia",
  "Sierra Leonean": "Sierra Leone",
  "Singaporean": "Singapore",
  "Slovak": "Slovakia",
  "Slovenian": "Slovenia",
  "South African": "South Africa",
  "Spanish": "Spain",
  "Spirit Lake Dakota/Cheyenne River Lakota": "United States of America",
  "Sri Lankan": "Sri Lanka",
  "Sudanese": "Sudan",
  "Swedish": "Sweden",
  "Swiss": "Switzerland",
  "Syrian": "Syria",
  "Taiwanese": "Taiwan",
  "Tanzanian": "Tanzania",
  "Thai": "Thailand",
  "Tlingit": "United States of America",
  "Trinidad and Tobagonian": "Trinidad and Tobago",
  "Tunisian": "Tunisia",
  "Turkish": "Turkey",
  "Ugandan": "Uganda",
  "Ukrainian": "Ukraine",
  "Uruguayan": "Uruguay",
  "Uzbekistani": "Uzbekistan",
  "Venezuelan": "Venezuela",
  "Vietnamese": "Vietnam",
  "Welsh": "United Kingdom",
  "Yugoslavian": "Serbia",
  "Zimbabwean": "Zimbabwe"
};

function cleanNationality(nationality) {
  return nationality ? nationality.trim() : "";
}

function getDisplayCountryName(country) {
  const aliases = {
    "Israel": "Occupied Palestinian Territories"
  };

  return aliases[country] || country;
}

function getDisplayNationalityName(nationality) {
  const aliases = {
    "Israeli": "IllegalSettler"
  };

  return aliases[nationality] || nationality;
}
